# This is a basic workflow that is manually triggered

name: Manual Update 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: false
  release:
    types: [published]


jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Latest Tag
        id: latest_tag
        run: |
          tag=${{ github.event.inputs.version }}
          if [ -z "$tag" ]
          then
            tag=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/tags" | jq -r '.[0].name')
          fi
          echo "{latest_tag}={tag}" >> $GITHUB_OUTPUT
      - name: Update Gist
        env:
          GIST_ID: ${{ secrets.GIST_UPDATE_ID }}
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
          APP_NAME: 'AnimesList10'
        run: |
          python update.py "${GITHUB_OUTPUT.latest_tag}" 
